import os

DEBUG = True
KEY = 'master'
ACTIVATION_EXPIRE_DAYS = 5
TOKEN_EXPIRE_HOURS = 1
TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTU0JJIiwic3ViIjoibGRhcEFQSSIsImV4cCI6MTYwNDc5NDMxNiwiaWF0IjoiMTU0MTYzNTkxNiJ9.TC2MkXso_P6J5kU-ZoigjA2TiPo4g3vtMkjq3BAKA-k'
